// <auto-generated />
namespace TravelTripProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v23));
        
        string IMigrationMetadata.Id
        {
            get { return "202204112352042_v2.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
